### ISSUE TITLE
launch.json 是否配置错误？还是我使用姿势有问题？

### ISSUE THREAD

**Issue by tjx666** [Discreater/Bilibili-Live-Danmaku-vscode#1]
要像下面这样配置才能正常启动扩展：
![screenshot_2020-05-30_11-47-44](https://user-images.githubusercontent.com/41773861/83318903-c8a9e800-a26b-11ea-9e27-5963328badef.png)

**Comment by Discreater** [comment]
感谢指出，发布版本应该是没问题的

**Comment by Discreater** [comment]
感谢指出，发布版本应该是没问题的
