### ISSUE TITLE
输入房间号后链接秒断，删了插件再装还是不行

### ISSUE THREAD

**Issue by dorahasadream** [Discreater/Bilibili-Live-Danmaku-vscode#10]
面板显示
[21:02:24] 已断开连接
[21:02:24]

**Comment by Discreater** [comment]
修好了，但是忘记了vscode market的发布账号🙈

**Comment by Discreater** [comment]
已更新

**Comment by lizyChy0329** [comment]
现在还是秒断
![image](https://github.com/user-attachments/assets/01f66822-9ae9-4a99-acb1-65f5581fb17d)

**Comment by Discreater** [comment]
有空看看，可能协议改了，不保证能修好

**Comment by Discreater** [comment]
已修复
